module.exports = {
  countryCodes: [
    "AM",
    "AU",
    "BT",
    "CA",
    "CH",
    "CN",
    "DE",
    "DK",
    "ES",
    "FR",
    "GB",
    "GR",
    "IE",
    "IN",
    "IR",
    "IT",
    "JP",
    "KG",
    "KR",
    "MT",
    "NL",
    "PK",
    "PL",
    "PT",
    "RO",
    "RU",
    "SE",
    "SG",
    "SI",
    "SY",
    "TH",
    "TM",
    "TW",
    "US"
  ],
  subCategories: {
    1: "MP3",
    2: "Recorder",
    3: "Radio",
    4: "Recording Pen",
    5: "Headphone",
    6: "Bluetooth Headphone",
    7: "Speakers",
    8: "Audio",
    9: "Television",
    10: "DVD",
    11: "Home Theater System",
    13: "Car Video",
    14: "Video Accessory",
    15: "Laptop",
    16: "Netbook",
    17: "Desktop",
    18: "Monitor",
    19: "Projector",
    20: "Printer",
    21: "Computer Setup",
    22: "Computer Accessory",
    23: "Digital Camera",
    24: "SLR camera",
    25: "Film Camera",
    27: "Camcorder",
    28: "Camera accessories",
    29: "Office Phone",
    31: "Touch Screen Phone",
    32: "Smart Phone",
    33: "Cell Phone Accessory",
    34: "CD",
    35: "DVD",
    36: "Audio Book",
    38: "Game",
    39: "Download Games",
    40: "Game Accessory",
    41: "Washing Machine",
    42: "Refrigerator",
    43: "Microwave",
    44: "Water Heater",
    45: "Coffe Machine",
    46: "Lamp",
    47: "Air Conditioner",
    48: "Fan"
  }
}